name: "Development Build"
on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  
  DeployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:

      - name: Deploy
        run: echo I am deploying the api to AWS

      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOST_NAME : ${{ secrets.HOST_NAME  }}
          USER_NAME : ${{ secrets.USER_NAME  }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          APP_DIR: ${{secrets.APP_DIR}}
          SERVICE_NAME: ${{secrets.SERVICE_NAME}}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
            cd ${APP_DIR} &&
            git pull &&
            echo -e "Jamali123*\n" | sudo -S systemctl restart ${SERVICE_NAME} "

  Test-Remote:
    name: Test Remote Deployment
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment:
      name: Development

    steps:
    - name: Test application
      run: |
        sleep 5
        curl ${{ secrets.HOST_NAME  }}:${{ secrets.PORT  }}/health | grep "template api"
